apiVersion: batch/v1
kind: Job
metadata:
  name: pubmed-baseline-job
spec:
  template:
    metadata:
      name: pubmed-baseline-job
    spec:
      containers:
      - name: pubmed-baseline
        image: 698471419283.dkr.ecr.eu-central-1.amazonaws.com/data-digger-pubmed:latest
        resources:
          requests:
            memory: "8Gi"
            cpu: "4"
          limits:
            memory: "16Gi"
            cpu: "6"
        command: ["sh", "-c", "./data-digger-etl/scripts/load-pubmed.sh pubmed-baseline-2-postgres"]
        env:
          - name: ENVIRONMENT
            value: "production"
          - name: POSTGRES_DATABASE
            valueFrom:
              configMapKeyRef:
                name: pubmed-datadigger-config
                key: POSTGRES_DATABASE
                optional: false
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: pubmed-datadigger-config
                key: POSTGRES_USER
                optional: false
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: pubmed-datadigger-config
                key: POSTGRES_PASSWORD
                optional: false
          - name: AWS_STORAGE_BUCKET
            valueFrom:
              configMapKeyRef:
                name: pubmed-datadigger-config
                key: AWS_STORAGE_BUCKET
                optional: false
          - name: AWS_REGION
            valueFrom:
              configMapKeyRef:
                name: pubmed-datadigger-config
                key: AWS_REGION
          - name: THREAD_POOL_SIZE
            valueFrom:
              configMapKeyRef:
                name: pubmed-datadigger-config
                key: THREAD_POOL_SIZE
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              configMapKeyRef:
                name: pubmed-datadigger-config
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              configMapKeyRef:
                name: pubmed-datadigger-config
                key: AWS_SECRET_ACCESS_KEY
      restartPolicy: Never
      nodeSelector:
        role: large-workloads
      tolerations:
      - key: "type"
        operator: "Equal"
        value: "large-workloads"
        effect: "NoSchedule"