apiVersion: batch/v1
kind: CronJob
metadata:
  name: pubmed-updates-cronjob
spec:
  schedule: "0 8 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          name: pubmed-updates-cronjob
        spec:
          containers:
          - name: pubmed-updates
            image: 698471419283.dkr.ecr.eu-central-1.amazonaws.com/data-digger-pubmed:latest
            resources:
              requests:
                memory: "8Gi"
                cpu: "4"
              limits:
                memory: "8Gi"
                cpu: "4"
            command: ["/bin/sh"]
            args:
            - -c
            - >-
              ./data-digger-etl/scripts/load-pubmed.sh pubmed-updates-2-postgres &&
              ./data-digger-etl/scripts/load-pubmed.sh pubmedcentral-s3-seed &&
              ./data-digger-etl/scripts/load-pubmed.sh pubmedcentral-s3-synchronize
            env:
              - name: ENVIRONMENT
                value: "production"
              - name: POSTGRES_DATABASE
                valueFrom:
                  configMapKeyRef:
                    name: pubmed-datadigger-config
                    key: POSTGRES_DATABASE
                    optional: false
              - name: POSTGRES_USER
                valueFrom:
                  configMapKeyRef:
                    name: pubmed-datadigger-config
                    key: POSTGRES_USER
                    optional: false
              - name: POSTGRES_PASSWORD
                valueFrom:
                  configMapKeyRef:
                    name: pubmed-datadigger-config
                    key: POSTGRES_PASSWORD
                    optional: false
              - name: AWS_STORAGE_BUCKET
                valueFrom:
                  configMapKeyRef:
                    name: pubmed-datadigger-config
                    key: AWS_STORAGE_BUCKET
                    optional: false
              - name: AWS_REGION
                valueFrom:
                  configMapKeyRef:
                    name: pubmed-datadigger-config
                    key: AWS_REGION
              - name: THREAD_POOL_SIZE
                valueFrom:
                  configMapKeyRef:
                    name: pubmed-datadigger-config
                    key: THREAD_POOL_SIZE
          restartPolicy: OnFailure
          nodeSelector:
            role: large-workloads
          tolerations:
          - key: "type"
            operator: "Equal"
            value: "large-workloads"
            effect: "NoSchedule"