apiVersion: batch/v1
kind: CronJob
metadata:
  name: pubmed-fulltext-xml-job
spec:
  schedule: "0 8 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          name: pubmed-fulltext-xml-job
        spec:
          containers:
          - name: pubmed-fulltext-xml
            image: 698471419283.dkr.ecr.eu-central-1.amazonaws.com/data-digger-pubmed-fulltext-xml:3.0
            resources:
              requests:
                memory: "4Gi"
                cpu: "2"
              limits:
                memory: "8Gi"
                cpu: "4"
            command: ["bash", "/usr/local/bin/script.sh"]
            envFrom:
            - configMapRef:
                name: pubmed-fulltext-xml-configmap
          restartPolicy: OnFailure
          nodeSelector:
            role: large-workloads
          tolerations:
          - key: "type"
            operator: "Equal"
            value: "large-workloads"
            effect: "NoSchedule"