apiVersion: batch/v1
kind: CronJob
metadata:
  name: pubmed-updates-cronjob
spec:
  schedule: "0 8 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          name: pubmed-updates-cronjob
        spec:
          containers:
          - name: pubmed-updates
            image: 698471419283.dkr.ecr.eu-central-1.amazonaws.com/data-digger-pubmed:latest
            command: ["sh", "-c", "./data-digger-etl/scripts/load-pubmed.sh pubmed-updates-2-postgres"]
            env:
              - name: ENVIRONMENT
                value: "production"
              - name: POSTGRES_DATABASE
                valueFrom:
                  configMapKeyRef:
                    name: pubmed-datadigger-config
                    key: POSTGRES_DATABASE
                    optional: false
              - name: POSTGRES_USER
                valueFrom:
                  configMapKeyRef:
                    name: pubmed-datadigger-config
                    key: POSTGRES_USER
                    optional: false
              - name: POSTGRES_PASSWORD
                valueFrom:
                  configMapKeyRef:
                    name: pubmed-datadigger-config
                    key: POSTGRES_PASSWORD
                    optional: false
          restartPolicy: OnFailure