[package]
name = "ranking"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.4" }
clap_derive = "4.5.4"
dotenv = "0.15.0"
postgres = "0.19.7"
