FROM --platform=linux/amd64 maven:3.9.6 AS build

WORKDIR /usr/src/app

COPY . .
RUN mvn clean install -DskipTests
RUN cd data-digger-etl
RUN mvn package assembly:single -DskipTests
RUN cd ..

FROM --platform=linux/amd64 openjdk:21

WORKDIR /usr/src/app
COPY --from=build /usr/src/app .

RUN mkdir /config
VOLUME /config

RUN chmod +x baseline_init.sh

CMD ["sh", "-c", "./baseline_init.sh"]