-- Create Full Text Job Table
CREATE TABLE IF NOT EXISTS fulltextdownloads
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    identifier character varying(60),
    location character varying(200),
    year smallint,
    state smallint,
    "timestamp" timestamp without time zone,
    CONSTRAINT fulltextdownloads_pkey PRIMARY KEY (id),
    CONSTRAINT fulltextdownloads_identifier_key UNIQUE (identifier)
);

-- Load Full Text Jobs from the Link Table
INSERT INTO fulltextdownloads (identifier, location, year, state, timestamp)
SELECT l.pmc, null, MAX(r.year), 0, MAX(l.timestamp) FROM 
linktable l JOIN records r ON r.identifier = l.pubmed
LEFT JOIN fulltextdownloads ft ON ft.identifier = l.pmc
WHERE ft.identifier IS NULL
GROUP BY l.pmc;